services:
  ml-pipeline:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION=us-east-2
    volumes:
      - .:/app

  dev:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION=us-east-2
    volumes:
      - .:/app
    command: tail -f /dev/null  # Keep container running
    stdin_open: true  # docker run -i
    tty: true        # docker run -t
